version: "3.9"

services:
  db:
   image: postgres
   volumes:
     - ./data/db:/var/lib/postgresql/data
   restart: always
   environment:
     - POSTGRES_DB=orders
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   container_name: orders_db
  web:
    container_name: order_online
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - ./online_ordering/.env
    ports:
      - "8000:8000"
    depends_on:
      - db