# Generated by Django 4.1.1 on 2022-10-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_items',
            field=models.IntegerField(default=1),
        ),
    ]
